### ISSUE TITLE
unexpected IllegalStateException thrown when originalSession expires

### ISSUE THREAD

**Issue by dfex55** [hazelcast/hazelcast-wm#49] opened 2017-04-10 10:49 UTC
HazelcastHttpSession.isNew() throws IllegalStateException when delegated to an invalidated originalSession.

**prerequisites:**
- containersession (originalSession) timeout is smaller than max-idle-seconds of the hazelcast map storing sessions for HazelcastHttpSession

**Steps to reproduce:**
1. create a valid containersession (originalSession) and HazelcastHttpSession
-> containersession id and hazelcast session id will be stored in cookie
2. let originalSession timeout
-> cookies are untouched
3. call HazelcastHttpSession.isNew() before max-idle-seconds of hazelcast map is reached
-> HazelcastHttpSession will be retrieved through cookie
4. "unexpected" IllegalStateException is thrown

**expected behavior:**
calling HazelcastHttpSession.isNew() returns false, when:
- HazelcastHttpSession is valid
- HazelcastHttpSession is not new
- HazelcastHttpSession is fetched through the hazelcast session cookie
- originalSession is invalidated

**expected because:**
- repeating steps 1-4 without HazelcastHttpSession does not throw an IllegalStateException
-> actually isNew() would return true and session data is lost, but no exception

**comments:**
- The originalSession is stored during creation of HazelcastHttpSession and stays there.
- After the timeout of originalSession the application container will create a new containersession, but the HazelcastHttpSession continues to point to the old invalidated original Session.
- Delegating HazelcastHttpSession.isNew() to the originalSession throws an IllegalStateException (which is expected by spec), but not programatically, because HazelcastHttpSession is valid and the new containersession is valid.

**Comment by dfex55** [comment] 2017-04-10 13:18
btw: besides .isNew, this also applies for
- .getSessionContext
- .invalidate

and
- .getAttributeNames
- .getValueNames
- .getAttribute

if these are used internally bei hazelcast-wm.

What about completely removing references to the originalSession?

**Comment by emre-aydin** [comment] 2017-04-12 07:29
Hi @dfex55,

Thanks for reporting the problem in detail. We're generally trying to keep the original session and Hazelcast session in sync. That's why we recommend having the session timeout value and max-idle the same. 

In case the original session times out but max-idle is not expired (probably because the session is active on another node), `isNew` should not throw `IllegalStateException`, but if the Hazelcast session is timed out as well (which means max-idle is expired), `IllegalStateException` should be thrown. 

Does this make sense? Can you please provide tests that reproduce the two scenarios above if these make sense?

**Comment by emre-aydin** [comment] 2017-07-20 06:44
@dfex55 any updates? Does my previous comment make sense?

**Comment by mesutcelik** [comment] 2018-04-27 13:56
closing this one. please feel free to reopen if you have any update.

**Closed by mesutcelik** 2018-04-27 13:56 UTC
